Update 2000-01-01-swift.md
nastoletni/faq pull request #11
Opened 2017-09-09 18:17 UTC by mmiller54

Dodane informacje nt. Swift i źródeł do nauki

2017-09-09 19:05 UTC, Albert221 requested changes

2017-09-09 19:05 UTC, Albert221 commented on _posts/2000-01-01-swift.md
> +Swift to język programowania stworzony do pisania natywnych aplikacji na systemy iOS, macOS, watchOS i tvOS
Dodaj kropkę na koniec zdania

2017-09-09 19:05 UTC, Albert221 commented on _posts/2000-01-01-swift.md
> +Aby zacząć pisać w Swift, potrzebujesz komputera z macOS z zainstalowanym środowiskiem programistycznym [Xcode], oraz [konto deweloperskie Apple]
i tutaj też

2017-09-09 19:05 UTC, Albert221 commented
Jest dobrze, dodaj tylko te kropki i merge'uję

2017-09-09 19:10 UTC, Albert221 requested changes

2017-09-09 19:10 UTC, Albert221 commented on _posts/2000-01-01-swift.md
> +- [iOS 11 & Swift 4: From Beginner to Paid Professional] - bardzo dobry kurs dla początkujących, Mark Price bardzo dobrze wprowadza w środowisko, wszystko jest wytłumaczone jasno i zwięźle. Warto pol
A tutaj zapomniałeś dodać linka na sam dół.

2017-09-09 20:28 UTC, mmiller54 commented
Poszło

2017-09-10 13:31 UTC, merged

2017-09-10 13:31 UTC, Albert221 commented
Thanks! :beers: