Added new section with resources and add link in gamedev section
nastoletni/faq pull request #7
Opened 2017-08-08 10:17 UTC by szczopek7

2017-08-08 16:52 UTC, szczopek7 commented
Poprawiłem i jeszcze coś dodałem, w najbliższym czasie pouzupełniam.

2017-08-10 09:01 UTC, Albert221 requested changes

2017-08-10 09:01 UTC, Albert221 commented on index.html
> +                <h2 id="darmowe-grafika">Darmowa grafika</h2>
Patrz dokładniej :P jeszcze błąd siedzi w `id`

2017-08-10 09:01 UTC, Albert221 commented on index.html
> +                <h2 id="ue">Unreal Engine 4</h2>
Zmień odnośnik na pełne `unreal-engine`

2017-08-10 09:01 UTC, Albert221 commented on index.html
> +                    <li><a href="#ue">Unreal Engine</a></li>
Nie zapomnij o zmianie odnośnika tutaj

2017-08-10 09:01 UTC, Albert221 commented on index.html
> +                    <li><a href="#darmowe-grafika">Darmowa grafika</a></li>
...i tutaj też

2017-08-10 10:26 UTC, szczopek7 commented
Teraz już chyba wszystko, w pracy siedzę to na szybko poprawiam jak mam chwilę.

2017-08-10 11:43 UTC, Albert221 approved these changes

2017-08-10 11:43 UTC, merged